name: LuckyLedger
options:
  bundleIdPrefix: com.luckyledger
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""  # Add your team ID here

targets:
  LuckyLedger:
    type: application
    platform: iOS
    sources:
      - LuckyLedger
    settings:
      base:
        INFOPLIST_FILE: LuckyLedger/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.luckyledger.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        TARGETED_DEVICE_FAMILY: "1,2"  # iPhone and iPad
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic

  LuckyLedgerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - LuckyLedgerTests
    dependencies:
      - target: LuckyLedger
    settings:
      base:
        INFOPLIST_FILE: LuckyLedgerTests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.luckyledger.app.tests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/LuckyLedger.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/LuckyLedger"
        BUNDLE_LOADER: "$(TEST_HOST)"

schemes:
  LuckyLedger:
    build:
      targets:
        LuckyLedger: all
        LuckyLedgerTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - LuckyLedgerTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
