name: HouseholdTracker
options:
  bundleIdPrefix: com.householdtracker
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""  # Add your team ID here

targets:
  HouseholdTracker:
    type: application
    platform: iOS
    sources:
      - HouseholdTracker
    settings:
      base:
        INFOPLIST_FILE: HouseholdTracker/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.householdtracker.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        TARGETED_DEVICE_FAMILY: "1,2"  # iPhone and iPad
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic

  HouseholdTrackerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - HouseholdTrackerTests
    dependencies:
      - target: HouseholdTracker
    settings:
      base:
        INFOPLIST_FILE: HouseholdTrackerTests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.householdtracker.app.tests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/HouseholdTracker.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/HouseholdTracker"
        BUNDLE_LOADER: "$(TEST_HOST)"

schemes:
  HouseholdTracker:
    build:
      targets:
        HouseholdTracker: all
        HouseholdTrackerTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - HouseholdTrackerTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
