#!/usr/bin/env python3
"""
Integrate generated icons into _icons.html template.
Extracts SVG paths from generated files and creates the Jinja macro template.
"""

import re
from pathlib import Path

def extract_svg_content(svg_path: Path) -> str:
    """Extract the path data from a potrace-generated SVG."""
    content = svg_path.read_text()

    # Extract the <g> element with transform and paths
    g_match = re.search(r'<g[^>]*>(.*?)</g>', content, re.DOTALL)
    if not g_match:
        return ""

    g_content = g_match.group(0)

    # Get transform attribute
    transform_match = re.search(r'transform="([^"]*)"', g_content)
    transform = transform_match.group(1) if transform_match else ""

    # Extract all path d attributes
    paths = re.findall(r'<path d="([^"]*)"', g_content)

    return transform, paths


def generate_icons_html(icons_dir: Path) -> str:
    """Generate the _icons.html template content."""

    # Header
    output = """{# Cat-themed icon macros for Lucky Ledger - Generated by DALL-E 3 #}
{# Usage: {% from "_icons.html" import icon %}  then  {{ icon('cat-happy', size='md') }} #}

{% macro icon(name, size='md', class='') %}
{%- set sizes = {'sm': '16', 'md': '20', 'lg': '24', 'xl': '32', '2xl': '48'} -%}
{%- set s = sizes.get(size, '20') -%}
<svg viewBox="0 0 1024 1024" width="{{ s }}" height="{{ s }}" class="inline-block {{ class }}" fill="currentColor" aria-hidden="true">
"""

    # Process each icon
    icon_files = sorted(icons_dir.glob("*.svg"))

    for i, svg_path in enumerate(icon_files):
        name = svg_path.stem
        if name.startswith("cat-") or name == "lucky-ledger-logo":
            transform, paths = extract_svg_content(svg_path)

            if not paths:
                print(f"Warning: No paths found in {name}")
                continue

            # Add conditional for this icon
            if i == 0:
                output += f'{{% if name == \'{name}\' %}}\n'
            else:
                output += f'{{%- elif name == \'{name}\' -%}}\n'

            # Add the transformed group with paths
            output += f'<g transform="{transform}">\n'
            for path_d in paths:
                output += f'<path d="{path_d}"/>\n'
            output += '</g>\n'

    # Add fallback and close
    output += """{%- else -%}
<!-- Fallback: simple cat face -->
<g transform="translate(0.000000,1024.000000) scale(0.100000,-0.100000)">
<circle cx="5120" cy="5120" r="4000" fill="none" stroke="currentColor" stroke-width="200"/>
</g>
{%- endif -%}
</svg>
{%- endmacro %}
"""

    return output


def main():
    icons_dir = Path(__file__).parent / "generated_icons"
    output_path = Path(__file__).parent.parent / "templates" / "_icons.html"

    # Backup existing file
    if output_path.exists():
        backup_path = output_path.with_suffix(".html.bak")
        backup_path.write_text(output_path.read_text())
        print(f"Backed up existing _icons.html to {backup_path.name}")

    # Generate new content
    content = generate_icons_html(icons_dir)

    # Write to file
    output_path.write_text(content)
    print(f"Generated new _icons.html with {len(list(icons_dir.glob('*.svg')))} icons")
    print(f"Output: {output_path}")


if __name__ == "__main__":
    main()
